[build]
  command = "vite build"
  publish = "dist"

[[headers]]
  for = "/Irene Hagstroem_Profile.pdf"
  [headers.values]
    Content-Disposition = "attachment; filename=\"Irene Hagstroem_Profile.pdf\""
    Content-Type = "application/pdf"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200